export { DeckDetailsPageAsync as DeckDetailsPage } from './deck-details-page/ui/deck-details-page.async'
export { DecksPageAsync as DecksPage } from './decks-page/ui/decks-page.async'
export { ForgotPasswordPageAsync as ForgotPasswordPage } from './forgot-password-page/ui/forgot-password-page.async'
export { NotFoundPageAsync as NotFoundPage } from './not-found-page/ui/not-found-page.async'
export { ProfilePageAsync as ProfilePage } from './profile-page/ui/profile-page.async'
export { SingInPageAsync as SingInPage } from './sing-in-page/ui/sing-in-page.async'
export { SingUpPageAsync as SingUpPage } from './sing-up-page/ui/sing-up-page.async'
