export type TypographyVariantType =
    | 'body1'
    | 'body2'
    | 'error'
    | 'h1'
    | 'h2'
    | 'h3'
    | 'large'
    | 'link1'
    | 'link2'
    | 'overline'
    | 'span'
    | 'subtitle1'
    | 'subtitle2'
